package com.marchnetworks.health.event;

public enum HealthEventEnum
{
	DEVICE_ONLINE,
	DEVICES_OFFLINE,
	DEVICES_UNREACHABLE,
	DEVICE_REBOOT,
	DEVICE_ALERT,
	DEVICE_ALERT_THRESHOLD_TRIGGERED,
	DEVICE_ALERT_USER_STATE_CHANGE,
	DEVICE_CHANGED,
	GROUP_CHANGED
}
