package com.marchnetworks.management.config.service;

public enum ConfigurationExceptionType
{
	NO_ERROR,
	INTERNAL_FAILURE,
	INVALID_SETTINGS,
	UNKNOWN_SNAPSHOT_STATE,
	DEVICE_CONFIG_NOT_FOUND,
	DEVICE_IMAGE_NOT_FOUND,
	DEVICE_IMAGE_ASSIGN,
	DEVICE_NOT_FOUND,
	DEVICE_FIRMWARE_FILE_NOT_FOUND,
	DEVICE_COMMUNICATION_FAILURE,
	DEVICE_FIRMWARE_BEING_APPLIED,
	DEVICE_CONFIG_FIRMWARE_IN_PROCESS;

	private ConfigurationExceptionType()
	{
	}
}
