package com.marchnetworks.server.event.health;

public enum HealthFaultTypeEnum
{
	QUERY_FAILED,
	ALERT_NOT_FOUND,
	ALERT_ALREADY_CLOSED,
	SECURITY,
	THRESHOLD_VALUE,
	THRESHOLD_NOT_FOUND,
	SCHEDULING_NOTIFICATION_FALIED,
	DELETE_NOTIFICATION_SCHEDULE_FALIED,
	NOTIFICATION_SCHEDULE_NOT_FOUND,
	SCHEDULING_QUARTZ_JOB_FALIED;

	private HealthFaultTypeEnum()
	{
	}
}

