package com.marchnetworks.license.exception;

public enum LicenseExceptionType
{
	NOT_FOUND,
	NOT_SUPPORTED,
	NOT_AUTHORIZED,
	LICENSE_PARSE_FAILED,
	LICENSE_VALIDATION_FAILED,
	LICENSE_SERVERID_NOT_FOUND,
	LICENSE_WRONG_SERVER,
	LICENSE_EXPIRED,
	LICENSE_NOT_YET_VALID,
	LICENSE_ALREADY_ADDED,
	LICENSE_COUNT_RECORDER,
	LICENSE_COUNT_CHANNEL,
	LICENSE_COUNT_APP,
	LICENSE_TYPE_INCOMPATIBLE,
	LICENSE_TRIAL_OVER_PERMANENT,
	LICENSE_RESOURCE_ERROR,
	LICENSE_COUNT_FROZEN,
	LICENSE_DEVICE_ERROR,
	LICENSE_NOT_SUPPORTED
}
