package com.marchnetworks.command.common.user;

public enum UserExceptionTypeEnum
{
	USER_NOT_FOUND,
	INSUFFICIENT_ACCESS_RIGHTS,
	CANNOT_SET_TERRITORY_ROOTS_TO_USER,
	CANNOT_MODIFY_SELF_TERRITORY_ASSIGMENT,
	CANNOT_MODIFY_SELF_PROFILE_ASSIGMENT,
	CANNOT_MODIFY_SELF_CERTIFICATE_ASSIGMENT,
	CANNOT_MODIFY_SELF_STATUS;

	private UserExceptionTypeEnum()
	{
	}
}
