package com.marchnetworks.management.config.events;

public enum ConfigNotificationType
{
	CONFIG_REGISTERED,
	CONFIG_REGISTERED_FAILED,
	CONFIG_APPLIED,
	CONFIG_APPLIED_FAILED,
	CONFIG_APPLY_PENDING,
	CONFIG_CHANGED,
	CONFIG_CHANGED_FAILED,
	CONFIG_FAILED,
	CONFIG_REMOVED,
	CONFIG_UNREGISTRATION_FAILED,
	SNAPSHOT_CHANGED,
	CONFIG_IMAGE_ASSIGNED,
	CONFIG_IMAGE_UNASSIGNED,
	CONFIG_IMAGE_UPGRADE_FAILED,
	CONFIG_IMAGE_UPGRADED,
	CONFIG_FIRMWARE_UPGRADE_PENDING,
	CONFIG_FIRMWARE_UPGRADED,
	CONFIG_FIRMWARE_UPGRADE_FAILED,
	CONFIG_MULTIPLE_APPLY,
	CONFIG_WAITING,
	CONFIG_APPLIED_NOT_MONITORING,
	CONFIG_PENDING_OFFLINE,
	CONFIG_PENDING_FIRMWARE
}
