package com.marchnetworks.management.config.events;

public enum ConfigNotificationReasonCode
{
	NO_REASON,
	REGISTER_FAIL_GET_DEVCONFIG_DATA,
	REREGISTRATION,
	CONFIG_APPLY_FAIL_GET_DEVICE,
	DEVICE_CONFIG_APPLY_FAILED,
	DEVICE_CHANGED_ERROR_GET_DEVICE,
	DEVICE_UPGRADE_FAILED,
	MODEL_SUBMODEL_DONOT_MATCH,
	NO_FIRMWARE_AVAIL,
	UPGRADE_PENDING,
	DEVICE_COMM_ERROR,
	DEVICE_GENERAL_ERROR,
	IMAGE_UPDATE_CHANGE_OTHER_DEV,
	DEVICE_IMAGE_NOT_FOUND,
	UNSUPPORTED_DEVICE_TYPE,
	REGISTRATION_FAILURE,
	UNREGISTRATION_FAILURE,
	FIRMWARE_CHANGED,
	PENDING_REQUEST_IN_PROGRESS,
	INVALID_CONFIG_XML
}
