package com.marchnetworks.command.common.topology;

public enum TopologyExceptionTypeEnum
{
	DEVICE_NOT_FOUND,
	GROUP_NOT_FOUND,
	RESOURCE_NOT_FOUND,
	ORPHAN_RESOURCE,
	INVALID_REQUEST,
	RESOURCE_ASSOCIATION_NOT_FOUND,
	INTERNAL_ERROR,
	CHANNEL_NOT_FOUND,
	DEVICE_ALREADY_REGISTERED,
	SECURITY,
	ALARM_SOURCE_NOT_FOUND,
	SWITCH_NOT_FOUND,
	AUDIO_OUTPUT_NOT_FOUND,
	MASS_REGISTRATION_FAILURE,
	STATION_ID_ALREADY_EXISTS,
	DEVICE_NOT_MARKED_FOR_REPLACEMENT,
	DEVICE_NOT_OFFLINE,
	INVALID_DEVICE_ADDRESS,
	DEVICE_CONFIGURATION_SNAPSHOT_NOT_EXISTS,
	DEVICE_FIRMWARE_VERSION_TOO_LOW,
	DEVICE_DISPLAYNAME_COLLISION,
	CANNOT_DELETE_TOPOLOGY_ROOTS,
	FOLDER_SET_AS_USER_TERRITORY,
	FOLDER_SET_TO_SCHEDULE,
	SINGLE_FOLDER_SET_TO_SCHEDULE
}
